### PR TITLE
Add basic unit test for version

### PR DESCRIPTION
**Pull request by lauramurgatroyd**
Closes https://github.com/vais-ral/CILViewer/issues/125

### CODE REVIEW

**Comment by lauramurgatroyd** [comment]
I am not sure if the action ran the test properly...

It says:

```
+ python -c 'import os; print ('\''TESTING IN THIS DIRECTORY'\'' , os.getcwd())'
+ python -m unittest discover test
...............................s....................
----------------------------------------------------------------------
Ran 52 tests in 2.884s

OK (skipped=1)
```

Why are there 52 tests?

**Comment by lauramurgatroyd** [comment]
For reference  in the iDVC repo when it runs the unit test it says:

```
..
----------------------------------------------------------------------
Ran 2 tests in 0.061s

OK
```

https://github.com/TomographicImaging/iDVC/runs/3640694826?check_suite_focus=true#step:4:317

And also prints the version number: `version 21.1.2-2-g15ead14`

**Comment by paskino** [comment]
I brought to the point of the tests running correctly. However, there's an error

```
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```
that is due to the base image not having libGL installed. 

Probably we need to modify the action to allow a specification of which packages we need and add the following to the image.

```
sudo apt install libgl1-mesa-glx
```

**Comment by lauramurgatroyd** [comment]
Thanks, I'll test adding that to the action repo now

**Comment by lauramurgatroyd** [comment]
Now failing because` ModuleNotFoundError: No module named 'ccpi.viewer.version'`

**Comment by lauramurgatroyd** [comment]
I made a test repo for trying to debug this. See: https://github.com/lauramurgatroyd/test-gh-actions/pull/6

**Comment by lauramurgatroyd** [comment]
It works now after copying the build.sh script from brem!

**Pull request merged**
