### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by lauramurgatroyd**
Mostly borrowed from @gfardell

### CODE REVIEW

**Comment by lauramurgatroyd** [comment]
Not sure whether to link the CIL developer guide or not as we follow *some* of it but not all - as most classes are VTK-style!

**Comment by paskino** [comment]
It's a good idea. I guess we should decide about the viewer conventions: for instance I think we use Qt's conventions for module names `verbSomeStuff` while VTK uses `VerbSomeStuff`, but this is not quite uniform throughout the code.

**Review by paskino — CHANGES_REQUESTED** [review]
See https://github.com/vais-ral/CILViewer/pull/224#issuecomment-1119367671

**Comment by lauramurgatroyd** [comment]
converting to draft until we have decided on https://github.com/vais-ral/CILViewer/issues/217

**Comment by lauramurgatroyd** [comment]
Some info was added about coding style, think it's ready to review again.

**Review by paskino — APPROVED** [review]

**Pull request merged**
